// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bars.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const listAggregatedBars = `-- name: ListAggregatedBars :many
SELECT time_bucket($1::interval, time)::timestamptz AS bucket,
       symbol,
       first(open, time)::float8 AS open,
       max(high)::float8 AS high,
       min(low)::float8 AS low,
       last(close, time)::float8 AS close,
       sum(volume)::bigint AS volume
FROM bars
WHERE symbol = $2
GROUP BY bucket, symbol
ORDER BY bucket ASC
`

type ListAggregatedBarsParams struct {
	Bucket string
	Symbol string
}

type ListAggregatedBarsRow struct {
	Bucket time.Time
	Symbol string
	Open   float64
	High   float64
	Low    float64
	Close  float64
	Volume int64
}

func (q *Queries) ListAggregatedBars(ctx context.Context, arg ListAggregatedBarsParams) ([]ListAggregatedBarsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAggregatedBars, arg.Bucket, arg.Symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAggregatedBarsRow
	for rows.Next() {
		var i ListAggregatedBarsRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Symbol,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBarsBySymbol = `-- name: ListBarsBySymbol :many
SELECT time, symbol, open, high, low, close, volume
FROM bars WHERE symbol = $1 ORDER BY time ASC
`

func (q *Queries) ListBarsBySymbol(ctx context.Context, symbol string) ([]Bar, error) {
	rows, err := q.db.QueryContext(ctx, listBarsBySymbol, symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bar
	for rows.Next() {
		var i Bar
		if err := rows.Scan(
			&i.Time,
			&i.Symbol,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBar = `-- name: UpsertBar :exec
INSERT INTO bars (time, symbol, high, open, low, close, volume)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (symbol, time) DO UPDATE SET
    high = excluded.high,
    open = excluded.open,
    low = excluded.low,
    close = excluded.close,
    volume = excluded.volume
`

type UpsertBarParams struct {
	Time   time.Time
	Symbol string
	High   float64
	Open   float64
	Low    float64
	Close  float64
	Volume int64
}

func (q *Queries) UpsertBar(ctx context.Context, arg UpsertBarParams) error {
	_, err := q.db.ExecContext(ctx, upsertBar,
		arg.Time,
		arg.Symbol,
		arg.High,
		arg.Open,
		arg.Low,
		arg.Close,
		arg.Volume,
	)
	return err
}

const upsertBars = `-- name: UpsertBars :exec
INSERT INTO bars (time, symbol, high, open, low, close, volume)
SELECT time, symbol, high, open, low, close, volume FROM unnest(
    $1::timestamptz[],
    $2::text[],
    $3::float8[],
    $4::float8[],
    $5::float8[],
    $6::float8[],
    $7::bigint[]
) AS t(time, symbol, high, open, low, close, volume)
ON CONFLICT (symbol, time) DO UPDATE SET
    high = excluded.high,
    open = excluded.open,
    low = excluded.low,
    close = excluded.close,
    volume = excluded.volume
`

type UpsertBarsParams struct {
	Time   []time.Time
	Symbol []string
	High   []float64
	Open   []float64
	Low    []float64
	Close  []float64
	Volume []int64
}

func (q *Queries) UpsertBars(ctx context.Context, arg UpsertBarsParams) error {
	_, err := q.db.ExecContext(ctx, upsertBars,
		pq.Array(arg.Time),
		pq.Array(arg.Symbol),
		pq.Array(arg.High),
		pq.Array(arg.Open),
		pq.Array(arg.Low),
		pq.Array(arg.Close),
		pq.Array(arg.Volume),
	)
	return err
}
