// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Bar struct {
	Time   time.Time
	Symbol string
	Open   float64
	High   float64
	Low    float64
	Close  float64
	Volume int64
}

type Strategy struct {
	ID         uuid.UUID
	Name       string
	Status     string
	Version    int64
	Identifier string
	CreatedAt  time.Time
}

type Subscription struct {
	Symbol    string
	CreatedAt time.Time
}
