// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlcgen

import (
	"context"
)

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE symbol = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, symbol string) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, symbol)
	return err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT symbol FROM subscriptions ORDER BY symbol
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var symbol string
		if err := rows.Scan(&symbol); err != nil {
			return nil, err
		}
		items = append(items, symbol)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (symbol) VALUES ($1)
ON CONFLICT (symbol) DO NOTHING
`

func (q *Queries) UpsertSubscription(ctx context.Context, symbol string) error {
	_, err := q.db.ExecContext(ctx, upsertSubscription, symbol)
	return err
}
