// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: strategies.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteStrategy = `-- name: DeleteStrategy :exec
DELETE FROM strategies WHERE id = $1
`

func (q *Queries) DeleteStrategy(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStrategy, id)
	return err
}

const getStrategy = `-- name: GetStrategy :one
SELECT id, name, status, version, identifier FROM strategies WHERE id = $1
`

type GetStrategyRow struct {
	ID         uuid.UUID
	Name       string
	Status     string
	Version    int64
	Identifier string
}

func (q *Queries) GetStrategy(ctx context.Context, id uuid.UUID) (GetStrategyRow, error) {
	row := q.db.QueryRowContext(ctx, getStrategy, id)
	var i GetStrategyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.Identifier,
	)
	return i, err
}

const listStrategies = `-- name: ListStrategies :many
SELECT id, name, status, version, identifier FROM strategies ORDER BY name
`

type ListStrategiesRow struct {
	ID         uuid.UUID
	Name       string
	Status     string
	Version    int64
	Identifier string
}

func (q *Queries) ListStrategies(ctx context.Context) ([]ListStrategiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listStrategies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStrategiesRow
	for rows.Next() {
		var i ListStrategiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Version,
			&i.Identifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStrategy = `-- name: UpsertStrategy :exec
INSERT INTO strategies (id, name, status, version, identifier)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    status = excluded.status,
    version = excluded.version,
    identifier = excluded.identifier
`

type UpsertStrategyParams struct {
	ID         uuid.UUID
	Name       string
	Status     string
	Version    int64
	Identifier string
}

func (q *Queries) UpsertStrategy(ctx context.Context, arg UpsertStrategyParams) error {
	_, err := q.db.ExecContext(ctx, upsertStrategy,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.Version,
		arg.Identifier,
	)
	return err
}
